import { useState } from "react";
import JSZip from "jszip";
import { X, Download, Code2, Globe, Gamepad2, Copy, Check, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { toast } from "@/hooks/use-toast";

interface ExportPanelProps {
  gameCode: string;
  gameTitle: string;
  slug?: string | null;
  isPublished: boolean;
  onClose: () => void;
}

type ExportOption = "html" | "embed" | "zip" | "itch";

function useClipboard(timeout = 2000) {
  const [copied, setCopied] = useState<string | null>(null);
  const copy = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopied(key);
    setTimeout(() => setCopied(null), timeout);
  };
  return { copied, copy };
}

export default function ExportPanel({ gameCode, gameTitle, slug, isPublished, onClose }: ExportPanelProps) {
  const [active, setActive] = useState<ExportOption>("html");
  const [zipping, setZipping] = useState(false);
  const { copied, copy } = useClipboard();

  const safeTitle = gameTitle.replace(/[^a-z0-9_-]/gi, "_").toLowerCase();
  const gameUrl = slug ? `${window.location.origin}/play/${slug}` : null;
  const embedCode = gameUrl
    ? `<iframe src="${gameUrl}" width="800" height="600" frameborder="0" allowfullscreen style="border-radius:8px;"></iframe>`
    : null;

  // ── HTML download ─────────────────────────────────────────────────────────
  const handleHtmlDownload = () => {
    const blob = new Blob([gameCode], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${safeTitle}.html`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "Downloaded!", description: `${gameTitle}.html saved.` });
  };

  // ── ZIP / itch.io download ────────────────────────────────────────────────
  const handleZipDownload = async (forItch = false) => {
    setZipping(true);
    try {
      const zip = new JSZip();
      zip.file("index.html", gameCode);
      if (forItch) {
        zip.file(
          "README.txt",
          `${gameTitle} — GameForge AI Export\n${"=".repeat(40)}\n\nUploading to itch.io:\n1. Create a new project on itch.io (itch.io/game/new)\n2. Set "Kind of project" to HTML\n3. Under "Uploads", upload this ZIP file\n4. Check "This file will be played in the browser"\n5. Set the viewport size to 800×600 (or your preferred size)\n6. Save & publish!\n\nGenerated by GameForge AI — gameforge.ai\n`,
        );
      } else {
        zip.file(
          "README.txt",
          `${gameTitle} — GameForge AI Export\n${"=".repeat(40)}\n\nHow to use:\n- Open index.html in any modern browser to play.\n- Requires internet connection for game libraries (Phaser / Three.js).\n- To host online, upload index.html to any static hosting service\n  (GitHub Pages, Netlify, Vercel, etc.).\n\nGenerated by GameForge AI — gameforge.ai\n`,
        );
      }
      const content = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(content);
      const a = document.createElement("a");
      a.href = url;
      a.download = forItch ? `${safeTitle}_itch.zip` : `${safeTitle}.zip`;
      a.click();
      URL.revokeObjectURL(url);
      toast({ title: "ZIP created!", description: forItch ? "Ready to upload to itch.io." : `${gameTitle}.zip saved.` });
    } finally {
      setZipping(false);
    }
  };

  const options: { id: ExportOption; icon: React.ReactNode; label: string; description: string }[] = [
    {
      id: "html",
      icon: <Download className="w-5 h-5" />,
      label: "Download HTML",
      description: "Single self-contained file you can open in any browser or host anywhere.",
    },
    {
      id: "embed",
      icon: <Code2 className="w-5 h-5" />,
      label: "Embed Code",
      description: "Paste an iframe into any website to embed the live hosted game.",
    },
    {
      id: "zip",
      icon: <Globe className="w-5 h-5" />,
      label: "Download ZIP",
      description: "ZIP archive with index.html and a README — ready to host on any static server.",
    },
    {
      id: "itch",
      icon: <Gamepad2 className="w-5 h-5" />,
      label: "Export to itch.io",
      description: "Correctly formatted ZIP with upload instructions — just drag and drop on itch.io.",
    },
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 backdrop-blur-sm" onClick={onClose}>
      <div
        className="relative w-full max-w-2xl mx-4 bg-card border border-border rounded-2xl shadow-2xl overflow-hidden"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-border">
          <div>
            <h2 className="font-display font-bold text-xl">Export Game</h2>
            <p className="text-sm text-muted-foreground mt-0.5">Choose how you'd like to share <span className="text-foreground font-medium">{gameTitle}</span></p>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} aria-label="Close export panel">
            <X className="w-5 h-5" />
          </Button>
        </div>

        <div className="flex divide-x divide-border">
          {/* Left: option list */}
          <nav className="w-52 shrink-0 py-3">
            {options.map((opt) => (
              <button
                key={opt.id}
                onClick={() => setActive(opt.id)}
                className={cn(
                  "w-full flex items-center gap-3 px-4 py-3 text-sm font-medium transition-colors text-left",
                  active === opt.id
                    ? "bg-primary/10 text-primary border-r-2 border-primary"
                    : "text-muted-foreground hover:text-foreground hover:bg-white/5",
                )}
              >
                {opt.icon}
                {opt.label}
              </button>
            ))}
          </nav>

          {/* Right: content area */}
          <div className="flex-1 p-6">
            {active === "html" && (
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold text-base mb-1">Download as HTML</h3>
                  <p className="text-sm text-muted-foreground">
                    Downloads a single <code className="bg-black/30 px-1 rounded text-xs">.html</code> file
                    containing the entire game. Open it locally or upload it to any web host.
                    Requires internet access for game libraries (Phaser / Three.js CDN).
                  </p>
                </div>
                <div className="rounded-lg bg-black/30 border border-border p-3 text-xs text-muted-foreground font-mono">
                  {safeTitle}.html
                </div>
                <Button onClick={handleHtmlDownload} className="w-full gap-2">
                  <Download className="w-4 h-4" /> Download {safeTitle}.html
                </Button>
              </div>
            )}

            {active === "embed" && (
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold text-base mb-1">Embed on your website</h3>
                  <p className="text-sm text-muted-foreground">
                    {isPublished && embedCode
                      ? "Copy the iframe below and paste it into any webpage. The game streams live from GameForge."
                      : "Publish your game first to generate an embed code. The game must be public to be embeddable."}
                  </p>
                </div>
                {isPublished && embedCode ? (
                  <>
                    <div className="relative">
                      <pre className="rounded-lg bg-black/50 border border-border p-4 text-xs font-mono text-green-400 overflow-x-auto whitespace-pre-wrap break-all">
                        {embedCode}
                      </pre>
                    </div>
                    <div className="flex gap-2">
                      <Button
                        onClick={() => copy(embedCode, "embed")}
                        variant="outline"
                        className="flex-1 gap-2"
                      >
                        {copied === "embed" ? <Check className="w-4 h-4 text-green-400" /> : <Copy className="w-4 h-4" />}
                        {copied === "embed" ? "Copied!" : "Copy embed code"}
                      </Button>
                      {gameUrl && (
                        <Button variant="outline" size="icon" asChild>
                          <a href={gameUrl} target="_blank" rel="noopener noreferrer" aria-label="Open game">
                            <ExternalLink className="w-4 h-4" />
                          </a>
                        </Button>
                      )}
                    </div>
                  </>
                ) : (
                  <div className="rounded-lg bg-amber-500/10 border border-amber-400/20 p-4 text-sm text-amber-300/80">
                    Publish your game from the editor top bar to unlock the embed code.
                  </div>
                )}
              </div>
            )}

            {active === "zip" && (
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold text-base mb-1">Download as ZIP</h3>
                  <p className="text-sm text-muted-foreground">
                    A ZIP archive containing <code className="bg-black/30 px-1 rounded text-xs">index.html</code> and
                    a README. Upload the contents to GitHub Pages, Netlify, Vercel, or any static host.
                  </p>
                </div>
                <ul className="text-xs text-muted-foreground space-y-1 bg-black/20 rounded-lg border border-border p-3">
                  <li className="flex gap-2"><span className="text-primary">📄</span> index.html — your game</li>
                  <li className="flex gap-2"><span className="text-primary">📝</span> README.txt — hosting instructions</li>
                </ul>
                <Button onClick={() => handleZipDownload(false)} disabled={zipping} className="w-full gap-2">
                  <Download className="w-4 h-4" /> {zipping ? "Creating ZIP…" : `Download ${safeTitle}.zip`}
                </Button>
              </div>
            )}

            {active === "itch" && (
              <div className="space-y-4">
                <div>
                  <h3 className="font-semibold text-base mb-1">Export to itch.io</h3>
                  <p className="text-sm text-muted-foreground">
                    Generates a ZIP formatted exactly as itch.io expects for HTML games, with step-by-step
                    upload instructions in the README.
                  </p>
                </div>
                <ol className="text-xs text-muted-foreground space-y-2 bg-black/20 rounded-lg border border-border p-3 list-none">
                  {[
                    "Download the ZIP below",
                    'Go to itch.io → Dashboard → "Create new project"',
                    'Set "Kind of project" to HTML',
                    "Upload the ZIP under Uploads and tick \u201cThis file will be played in the browser\u201d",
                    "Set viewport to 800×600 → Save & publish",
                  ].map((step, i) => (
                    <li key={i} className="flex gap-2">
                      <span className="text-primary font-bold shrink-0">{i + 1}.</span> {step}
                    </li>
                  ))}
                </ol>
                <Button onClick={() => handleZipDownload(true)} disabled={zipping} className="w-full gap-2 bg-[#fa5c5c] hover:bg-[#e04444] text-white border-0">
                  <Gamepad2 className="w-4 h-4" /> {zipping ? "Creating ZIP…" : "Download itch.io ZIP"}
                </Button>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
